- name: Ensure containerd is installed
  apt:
    name: containerd
    state: present
    update_cache: yes

- name: Generate containerd default config
  shell: |
    mkdir -p /etc/containerd
    containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Set SystemdCgroup to true
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Enable and restart containerd
  systemd:
    name: containerd
    enabled: yes
    state: restarted

- name: Load kernel modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Ensure br_netfilter and overlay are loaded
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Set sysctl parameters
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

- name: Apply sysctl parameters
  command: sysctl --system

- name: Get kubeadm join command from master
  shell: kubeadm token create --print-join-command
  register: join_output
  delegate_to: "{{ groups['k8s-master'][0] }}"
  run_once: true

- name: Set join command fact
  set_fact:
    worker_join_command: "{{ join_output.stdout }}"

- name: Create join script
  template:
    src: join.sh.j2
    dest: /tmp/kubeadm-join.sh
    mode: '0755'

- name: Run join script
  command: /tmp/kubeadm-join.sh
  args:
    creates: /etc/kubernetes/kubelet.conf
