---
- hosts: k8s-cluster
  become: true
  tasks:
    - name: Disable Swap
      shell: |
        swapoff -a && sed -i '/ swap / s/^/#/' /etc/fstab

    - name: Install Kubernetes prerequisites
      apt:
        name:
          - apt-transport-https
          - curl
        state: present

    - name: Add Kubernetes GPG key
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor -o /usr/share/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes repo
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: Install kubeadm, kubelet, kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold Kubernetes packages
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        #mark_hold: yes

    - name: Enable kubelet
      systemd:
        name: kubelet
        enabled: yes
