---
- name: Configure passwordless sudo for Ansible-managed users
  hosts: all
  become: true
  gather_facts: true

  vars:
    sudo_line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"

  tasks:

    - name: Set correct visudo path per OS
      set_fact:
        visudo_path: >-
          {{ '/usr/local/sbin/visudo' if ansible_os_family == 'FreeBSD'
             else '/usr/sbin/visudo' }}

    - name: Install sudo on Fedora using raw dnf (avoids dnf5 bug)
      raw: dnf install -y sudo
      when: ansible_distribution == "Fedora"

    - name: Install sudo on other systems
      package:
        name: sudo
        state: present
      when: ansible_os_family in ['Debian', 'FreeBSD'] or
            (ansible_os_family == 'RedHat' and ansible_distribution != "Fedora")

    - name: Create sudoers entry for passwordless sudo
      lineinfile:
        path: /etc/sudoers.d/{{ ansible_user }}
        create: yes
        mode: '0440'
        owner: root
        group: "{{ 'wheel' if ansible_os_family == 'FreeBSD' else 'root' }}"
        line: "{{ sudo_line }}"
        validate: "{{ visudo_path }} -cf %s"

    - name: Confirm passwordless sudo works
      command: sudo -n true
      register: sudo_test
      failed_when: sudo_test.rc != 0
      changed_when: false

    - name: Display confirmation
      debug:
        msg: "✅ Passwordless sudo configured for '{{ ansible_user }}' on {{ inventory_hostname }}"
